FROM node:14.18.3-alpine3.15

WORKDIR /usr/app

RUN export 

COPY package*.json ./

RUN npm install

COPY . .

ARG REACT_APP_CDN_URL

ENV REACT_APP_CDN_URL $REACT_APP_CDN_URL

ARG REACT_APP_API_URL

ENV REACT_APP_API_URL $REACT_APP_API_URL

RUN npm run build

RUN npm i -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]