version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging
    image: askrs-archives-server:staging
    container_name: askrs-archives-server
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - FIREBASE_ADMIN_TYPE=${FIREBASE_ADMIN_TYPE}
      - FIREBASE_ADMIN_PROJECT_ID=${FIREBASE_ADMIN_PROJECT_ID}
      - FIREBASE_ADMIN_PRIVATE_KEY_ID=${FIREBASE_ADMIN_PRIVATE_KEY_ID}
      - FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
      - FIREBASE_ADMIN_CLIENT_EMAIL=${FIREBASE_ADMIN_CLIENT_EMAIL}
      - FIREBASE_ADMIN_CLIENT_ID=${FIREBASE_ADMIN_CLIENT_ID}
      - FIREBASE_ADMIN_AUTH_URI=${FIREBASE_ADMIN_AUTH_URI}
      - FIREBASE_ADMIN_TOKEN_URI=${FIREBASE_ADMIN_TOKEN_URI}
      - FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL=${FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL}
      - FIREBASE_ADMIN_CLIENT_X509_CERT_URL=${FIREBASE_ADMIN_CLIENT_X509_CERT_URL}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
      args:
        - REACT_APP_CDN_URL=${REACT_APP_CDN_URL}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    image: askrs-archives-client:staging
    container_name: askrs-archives-client
    command: "serve -s build -l 3000"
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_CDN_URL=${REACT_APP_CDN_URL}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M

networks:
  app-network:
    driver: bridge

volumes:
    web-root:
      driver: local