version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging
    image: askrs-archives-server:staging
    container_name: askrs-archives-server
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
    image: askrs-archives-client:staging
    container_name: askrs-archives-client
    command: "serve -s build -l 3000"
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_CDN_URL = ${REACT_APP_CDN_URL}
      - REACT_APP_API_URL = ${REACT_APP_API_URL}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M

networks:
  app-network:
    driver: bridge

volumes:
    web-root:
      driver: local