version: '3.9'

services:
  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile.staging
    image: askrs-archives-server:staging
    container_name: askrs-archives-server
    command: npm run start
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
    image: askrs-archives-client:staging
    container_name: askrs-archives-client
    command: "serve -s build -l 3000"
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - "REACT_APP_CDN_URL = ${{ secrets.REACT_APP_CDN_URL }}"
      - "REACT_APP_API_URL = ${{ secrets.REACT_APP_API_URL }}"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M

networks:
  app-network:
    driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local