FROM node:14.18.3-alpine3.15

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY server server

WORKDIR /usr/src/app/server

ARG NODE_ENV=production

RUN npm install

RUN npm run build

EXPOSE 8080

CMD ["npm","start"]