FROM python:3.10.9-alpine AS prebuild

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY scripts scripts

COPY server server

WORKDIR /usr/src/app/scripts

RUN python data_extract/main.py

FROM node:14.18.3-alpine3.15 as build

COPY --from=prebuild /usr/src/app/server /usr/src/app/server

WORKDIR /usr/src/app/server

ARG NODE_ENV=production

RUN npm install

RUN npm run build

EXPOSE 8080

CMD ["npm","start"]