FROM node:14.18.3-alpine3.15

COPY --from=prebuild /usr/src/app/server /usr/src/app/server

WORKDIR /usr/src/app/server

ARG NODE_ENV=production

RUN npm install

RUN npm run build

EXPOSE 8080

CMD ["npm","start"]