import { Stats } from '../Generics';

export interface SkillDataModel {
  id_tag: string;
  refine_base: string | null;
  name_id: string;
  desc_id: string;
  refine_id: string | null;
  beast_effect_id: string | null;
  prerequisites: (string | null)[];
  next_skill: string | null;
  sprites: (string | null)[];
  stats: Stats;
  class_params: Stats;
  combat_buffs: Stats;
  skill_params: Stats;
  skill_params2: Stats;
  refine_stats: Stats;
  id_num: number;
  sort_id: number;
  icon_id: number;
  wep_equip: number;
  mov_equip: number;
  sp_cost: number;
  category: number;
  tome_class: number;
  exclusive: boolean;
  enemy_only: boolean;
  range: number;
  might: number;
  cooldown_count: number;
  assist_cd: boolean;
  healing: boolean;
  skill_range: number;
  score: number;
  promotion_tier: number;
  promotion_rarity: number;
  refined: boolean;
  refine_sort_id: number;
  wep_effective: number;
  mov_effective: number;
  wep_shield: number;
  mov_shield: number;
  wep_weakness: number;
  mov_weakness: number;
  wep_adaptive: number;
  mov_adaptive: number;
  timing_id: number;
  ability_id: number;
  limit1_id: number;
  limit1_params: number [];
  limit2_id: number;
  limit2_params: number[];
  target_wep: number;
  target_mov: number;
  passive_next: string | null;
  timestamp: string | null;
  random_allowed: number;
  min_lv: number;
  max_lv: number;
  tt_inherit_base: boolean;
  random_mode: number;
  limit3_id: number;
  limit3_params: number[];
  range_shape: number;
  target_either: boolean;
  distant_counter: boolean;
  canto_range: number;
  pathfinder_range: number;
  arcane_weapon: boolean;
}
